modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/ewewukek/mc-musketmod/issues"
[[mods]]
modId="musketmod"
version="${file.jarVersion}"
displayName="Musket Mod"
#updateJSONURL=""
displayURL="https://github.com/ewewukek/mc-musketmod"
#logoFile="musket.png"
credits="lilypuree and MikhailTapio for their contribution"
authors="ewewukek"
description='''
Small mod that adds craftable muskets and pistols.
'''
