modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
issueTrackerURL="https://github.com/ewewukek/mc-musketmod/issues"
[[mods]]
modId="musketmod"
version="${file.jarVersion}"
displayName="Musket Mod"
#updateJSONURL=""
displayURL="https://github.com/ewewukek/mc-musketmod"
#logoFile="musket.png"
authors="ewewukek"
description='''
Simple mod that adds a craftable musket.
'''
